### ISSUE TITLE
Building an upload mechanism for OAM

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#37]
Currently we're missing an upload mechanism for getting imagery into the HOT Open Imagery Network S3 bucket. The HOT bucket will be an available resource within OIN for aerial imagery to be uploaded and made available within OAM. 

@jflasher @anandthakker @scisco @lossyrob and myself have thought through some of this initial approach and want to list out an approach below. 

**We want to outline this approach for building v1 of an upload mechanism to get feedback from the wider group. Post comments/questions in comments below. We'll look to discuss on Gitter tomorrow during the weekly OAM chat.** 

****

_Goal: Build a mechanism to upload imagery and generate metadata for the HOT AWS S3 bucket._

#### Needs:  
  - provide a UI for users to fill out metadata  
  - license agreement  
  - validate geotiff
  - generate a valid meta.json file  
  - upload to S3  
  - add metadata to the catalog
    
#### Technical notes  
  - leverage users existing file storage (like Dropbox) to eliminate duplicating uploading large files and work around low-bandwidth environments  
  - provide a semi-authenticated method for reducing junk uploads and spam (can't be random uploads, need to verify user and purpose)  
  - eliminate any type of oAuth access to reduce complexity  
  - won't use auto AWS credential creation to reduce complexity and enable repurpose to other file storage systems  
  - use email as main source for feedback on progress

#### Narrative of how it would work 
This application will provide authenticated access to upload to the HOT S3 OIN bucket. The application will enable users to provide metadata information alongside an array of valid geotiff files to upload to OAM. The application will validate the geotiff, generate valid metadata, and push to the HOT S3 bucket. Users will receive an email report upon completion. The first iteration of an uploader will focus on giving token-based access to the HOT OAM node while removing the need to handle direct file uploading.

A browser-based web form will be used for filling out necessary metadata like provider, sensor, type, acquisition date. A user will also provide a list of available files to upload. These files can be stored on any public service, like Dropbox. To simplify authentication, API tokens will generated and made available for users with imagery to upload. The user will provide the token and submit their request. The user will receive a confirmation message that their submission is processing.

Once a user submits, a server-side process will begin to upload to a temporary HOT S3 bucket. The temporary bucket will be used to hold uploaded imagery. Once a file is uploaded to the temp bucket, the Upload API will check, validate, and generate a metadata file for the image. Image and metadata file will then be transferred to the official HOT OIN S3 bucket. Invalid files will be deleted. Once the entire process is done, the user will receive an email giving a report output of their submission. Errors will be listed for the user to troubleshoot and attempt to re-upload.The application will have a web form submission process as well as direct API access.

A simple process for generating and managing API tokens will be available through HOT. Tokens will be generated and managed for access to the upload API. Github will be the primary source for requesting a tokens. A more automated approach to API token generation can be built as the need arises.

**Comment by lossyrob** [comment]
Tagging @hectcastro and @notthatbreezy as they've been in discussions with me about this or similar problems.

**Comment by lossyrob** [comment]
@smit1678, that sounds reasonable. 
So to state the process back so I'm clear on it:
- the server side process would take a request that was:
  - API key, which would need to be validated
  - Metadata for the image set
  - list of images from a publicly accessible storage system (Dropbox or any HTTP URI, should it support s3 URI's as well?)
- files would be moved from their original storage to a temporary s3 bucket
- once that intermediate import is complete, kick off a process that has the list of s3 images similar to the metadata generation endpoint in the OAM server scope.
-  Either a reject message is sent back, or the OK, which means that the metadata is generated next to the images in the HOT bucket.
- On successful metadata generation, the images and metadata are moved to the HOT bucket, so that they are deleted from the temporary bucket.

And to add for OAM Server work:
- If a tile set is desired, a process kicks off with the new image set (in what ordering?) with any tile set metadata required (which might just be a unique identifier for the tile set). A similar email system is used to notify the user when the tile set is completed.

Sound right?

**Comment by hectcastro** [comment]
> #### Technical notes

> - won't use auto AWS credential creation to reduce complexity and enable repurpose to other file storage systems

Not sure I follow what this is making reference to.

> #### Narrative of how it would work

> This application will provide authenticated access to upload to the HOT S3 OIN bucket. The application will enable users to provide metadata information alongside an array of valid geotiff files to upload to OAM. The application will validate the geotiff, generate valid metadata, and push to the HOT S3 bucket. Users will receive an email report upon completion. The first iteration of an uploader will focus on giving token-based access to the HOT OAM node while removing the need to handle direct file uploading.

+1 to offloading the file upload directly to Amazon S3. We are starting up a new project internally that is planning to take the same appraoch. Not many gotchas uncovered yet because we haven't started implementation, but here is we we're tracking the discussion right now: https://github.com/azavea/raster-foundry/issues/7

That issue includes some links that walk through the implementation process, as well as links to JavaScript libraries that handle most of the client-side heavy lifting.

> A browser-based web form will be used for filling out necessary metadata like provider, sensor, type, acquisition date. A user will also provide a list of available files to upload. These files can be stored on any public service, like Dropbox. To simplify authentication, API tokens will generated and made available for users with imagery to upload. The user will provide the token and submit their request. The user will receive a confirmation message that their submission is processing.

> Once a user submits, a server-side process will begin to upload to a temporary HOT S3 bucket. The temporary bucket will be used to hold uploaded imagery. Once a file is uploaded to the temp bucket, the Upload API will check, validate, and generate a metadata file for the image.

We are hoping to use Amazon S3 callbacks to signal to the application when uploads are complete. According to the Amazon S3 documentation, we can wire up functions or notifications for the following events:

- `s3:ObjectCreated:*`
- `s3:ObjectCreated:Put`
- `s3:ObjectCreated:Post`
- `s3:ObjectCreated:Copy`
- `s3:ObjectCreated:CompleteMultipartUpload`

It is still unclear whether we'll use Amazon Lambda directly here, or ping the application with a message notifying it that something happened.

See also: http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html#supported-notification-event-types

> Image and metadata file will then be transferred to the official HOT OIN S3 bucket. Invalid files will be deleted. Once the entire process is done, the user will receive an email giving a report output of their submission. Errors will be listed for the user to troubleshoot and attempt to re-upload.The application will have a web form submission process as well as direct API access.

> A simple process for generating and managing API tokens will be available through HOT. Tokens will be generated and managed for access to the upload API. Github will be the primary source for requesting a tokens.

How does this work? Does this mean GitHub OAuth to try and associate their key with a known GitHub user?

> A more automated approach to API token generation can be built as the need arises.

Overall, this looks really well thought out. Thanks for writing it up.

**Comment by smit1678** [comment]
@lossyrob Sounds right.

> should it support s3 URI's as well

Good question. I don't see why not, although it may be useful to check to then take advantage of just moving with AWS and not stream into a bucket. 

> If a tile set is desired, a process kicks off with the new image set (in what ordering?) with any tile set metadata required (which might just be a unique identifier for the tile set). A similar email system is used to notify the user when the tile set is completed.

Do you see this as a checkbox within the web form -- users can select whether they want a tile set at the end of the upload? Do we want a tile set generated for every upload? 

Thanks for the notes and links @hectcastro 

> - won't use auto AWS credential creation to reduce complexity and enable repurpose to other file storage systems
>
Not sure I follow what this is making reference to.

We thought a bit about using the AWS SDK to create S3 credentials on the fly for users to upload directly to s3. But ultimately thought we could simplify by just using keys to authenticate against the upload API instead of generating and managing AWS users and credentials.  

> How does this work? Does this mean GitHub OAuth to try and associate their key with a known GitHub user?

My sentence may have been a little confusing. We won't be using any OAuth, we'll have a simple admin panel for API key generation, and then use either Github tickets for coordinating new users or a simple form for filling out a key request (the challenge with Github tickets will be email exchange to pass the generated key, not everyone may be willing to share their email publicly).
