### ISSUE TITLE
image licenses and metadata

### ISSUE THREAD

**Issue by sbsimo** [hotosm/OpenAerialMap#40]
Looking at OIN metadata (https://github.com/openimagerynetwork/oin-metadata-spec) we noticed that no specific information on licensing level is preserved: that seems normal as providers that want to contribute to OIN must agree to CC-BY 4.0 license (https://github.com/openimagerynetwork/oin-register).

On the contrary, OAM metadata (https://github.com/hotosm/OpenAerialMap/tree/master/metadata) include a field named License for storing "Usage license of the datasource. This determines visibility of the datasource for authenticated users".

Is this difference due to the fact that OAM is conceived for browsing data possibly coming from sources different from OIN?

Presently (OpenAerialMap beta), the browser does not require any authentication process and therefore all available data are accessible to any user. Is an authentication step foreseen in next OAM development? Until no authentication is available, images with more restricting licensing levels will be not displayed/not accessible trough OAM browser?

**Comment by smit1678** [comment]
@cgiovando Can you provide additional insight here regarding the metadata spec? The final metadata spec for OIN is listed here: https://github.com/openimagerynetwork/oin-metadata-spec. I think the spec was started within the OAM repo but moved to the OIN organization since that is the base for everything. One of the reasons that a license item was dropped from the spec is that everything will be CC-BY and so there is no need for that item. That was discussed among the group but can certainly be picked back up for discussion. 

> On the contrary, OAM metadata (https://github.com/hotosm/OpenAerialMap/tree/master/metadata) include a field named License for storing "Usage license of the datasource. This determines visibility of the datasource for authenticated users".

Not sure if this is relevant anymore since we're going with a single license. We may want to remove this data from this repo and point people to the OIN repo since this is a bit confusing having two metadata specs. 

> Presently (OpenAerialMap beta), the browser does not require any authentication process and therefore all available data are accessible to any user. Is an authentication step foreseen in next OAM development? Until no authentication is available, images with more restricting licensing levels will be not displayed/not accessible trough OAM browser?

From my understanding of what was agreed by the group is that levels of authentication won't and probably shouldn't happen. OAM will be a open repository of information and will reduce any barriers to using the data by having a single, very open license.

**Comment by lossyrob** [comment]
I think the thought here was, OIN imagery is only CC-BY licensed, but we didn't want to place the restriction on OAM. For now, OAM catalog indexes OIN only, however in the future it may pull from different sources. The OIN can provide technology and the framework for building other, differently-licensed datasets. For example, if there was a network for disaster-response-only licensed imagery, then that imagery could also be indexed by OAM. Perhaps that license has an expiration date, or can't be downloaded, or can only be used by certain individuals. As you mentioned @sbsimo, authentication would be required if there were licenses that only allowed usage by certain individuals. This would be a future enhancement to the OAM platform. For now, though, there is no imagery that is licensed other than by CC-BY by OAM, so the visibility is open.

I agree that having a spec hanging around that talks about some possible future version of OAM, with otherly-licensed imagery and authentication, is a confusion point, and could be dropped.
