### ISSUE TITLE
Tiles not available for Dar es Salaam imagery

### ISSUE THREAD

**Issue by maning** [hotosm/OpenAerialMap#46]
The TMS endpoint for Dare a Salam UAV imagery is not available anymore.
See: https://lists.openstreetmap.org/pipermail/hot/2016-June/012090.html

**Comment by PaulUithol** [comment]
See https://lists.openstreetmap.org/pipermail/hot/2016-June/012093.html. Since I'm able to log into Github again now, also adding here that I've been notified the imagery has moved to https://api.mapbox.com/v4/worldbank-education.pebkgmlc/page.html?access_token=pk.eyJ1Ijoid29ybGRiYW5rLWVkdWNhdGlvbiIsImEiOiJIZ2VvODFjIn0.TDw5VdwGavwEsch53sAVxA

**Comment by smit1678** [comment]
@PaulUithol Excellent, thanks. I updated the database with the new tiles. All fixed here. Will follow up on that thread as well.
