### ISSUE TITLE
Add browser-based uploads

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#56]
From [other OAM improvements](https://github.com/hotosm/OpenAerialMap/wiki/OAM-development-related-to-PacDID-project#other-oam-improvements), look to implement browser-based uploads.

**Comment by smit1678** [comment]
@mojodna insight from using tus.io on https://github.com/AmericanRedCross/posm-opendronemap-api. Also there is https://github.com/18F/voyage or a different approach https://github.com/Peer5/Sharefest.

**Comment by mojodna** [comment]
I implemented tus.io but haven't actually used it for anything... It seemed like a good idea at the time but may be overkill for that use-case.

For OAM, voyage looks really good and most appropriate. Uploads direct to S3 are probably best (using pre-signed URLs; it looks like this is what voyage uses).

The only initial con I see in using voyage is later making OAM less-dependent on S3 / the cloud. This could be mitigated by running an S3-compatible API locally (e.g. https://www.minio.io/) or by abstracting out the upload components (and possibly replacing them with a tus.io-powered implementation when not using S3).

**Comment by nbumbarger** [comment]
I had assumed that we would upload directly from the page to S3. That would involve adding an endpoint to the uploader-api that returns a pre-signed bucket URL (or other credentials), uploading directly from the page, then triggering the image processing as usual, using that URL.

**Comment by nbumbarger** [comment]
Visually, I'm was thinking that direct uploads should be triggered through another button on the __Imagery location__ line of the upload form, which will reveal a file input rather than a text field. I think that submitting the form should trigger an uncloseable progress modal to discourage users from navigating away from the page, although there are plenty of other ways to handle it (progress bar at bottom of form, under the file input, etc.). Are there any other ideas?

**Comment by nbumbarger** [comment]
Rather than going with a modal, we added a progress indicator that appears to the right of the submit button during file uploads, accompanied by the existing loading badge which appears in the center of the page.

![example](https://cloud.githubusercontent.com/assets/9471488/20899721/99737c02-baf9-11e6-9154-f5ca2f27aab7.png)

The form allows for multiple file uploads, and separately displays the progress of each.

**Comment by nbumbarger** [comment]
Direct uploads were added through these pull requests to the [API](https://github.com/hotosm/oam-uploader-api) and the [upload form](https://github.com/hotosm/oam-uploader).

The API has been given a new authenticated endpoint called `direct-upload`, which receives a form containing a file pointer and an output name, and saves uploaded files to a subdirectory called `uploads`.

When a file upload is initiated using the form, a progress bar appears to the right of the submit button, and any files that have been added are uploaded asynchronously before the form is submitted. When the files have finished uploading, the form is submitted as usual, and images that were uploaded instead of sent as a URL are given a `file://` prefix in the database. When the workers encounter images in the queue with this prefix, they search for the image locally rather than attempting to download it, then they remove it from local storage when the standard processing finishes.

**Comment by nbumbarger** [comment]
There were some failing tests in the PRs above, which should be fixed by [this PR](https://github.com/hotosm/oam-uploader-api/pull/53) to the API and [this PR](https://github.com/hotosm/oam-uploader/pull/52) to the upload form.

**Comment by smit1678** [comment]
This rolled out in https://github.com/hotosm/oam-uploader-api/pull/71. 👏
