### ISSUE TITLE
Indexing non-Open Imagery Network data

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#63]
Starting a discussion on the possibility of indexing non-OIN licensed data. Right now [Open Imagery Network nodes](https://github.com/openimagerynetwork/oin-register) provide the foundation for available imagery to be indexed. These nodes require that the imagery can be CC-BY 4.0 licensed. There are a number of other providers that license their data as CC-BY-SA or CC-BY-NC. The question is could OpenAerialMap tools and services include these other licenses when indexing? Can OAM provide access to imagery that is more than just a single license? 

I don't think the question is whether they can be integrated into an OIN node (assuming that it will stay with a CC-BY license only). 

Implications to think through: 

* Impact on tracing with OSM
* Mosaicking multiple licenses together into a TMS service

@cgiovando Other implications we need to discuss?

**Comment by cgiovando** [comment]
Thanks for starting this thread @smit1678 - In the original OAM vision we always wished for only truly open licenses such as CC0, but since we're using CC-BY at the moment (which already adds a clause), I'm open and I agree that we could include multiple license types.

If we keep the definition of "open" ..open for now, this would actually be a good exercise to help us think through what licenses are most appropriate for open EO data and bootstrap an effort to come up with a standard reference set (like CC licenses are for creative digital content).

One requirement on our side (HOT), as we're leading the process, would be that OSM tracing permission is agreed for any type of content. We'd have to confirm with the OSFM legal working group, but I believe that for example CC-BY-NC with an explicit permission to trace in OSM is OK.

Mosaicking should not be impacted if we're able to create those dynamically based on the type of license selected.

I would suggest we apply this discussion at OIN level rather than OAM. That would give providers the opportunity to host their own OIN imagery nodes.

**Comment by smit1678** [comment]
Thanks @cgiovando 👍 . So what you're saying is that it may be more beneficial if we bring this convo into OIN and have a larger discussion around the type of licenses that are exposed through the OIN standard? 

Others? cc @mojodna @wonderchook @ianschuler @mikelmaron @lossyrob

**Comment by wonderchook** [comment]
I agree that this should probably be an OIN thing. Then OAM can decide how to implement it. 

I'm also thinking about the best way to structure explicit permission for OSM as is suggested. I also think OSM might not be the only use case for this, though I don't know of a specific other one.

**Comment by smit1678** [comment]
To follow up here, there was an OIN discussion and decision on the open issue about multiple licenses: https://github.com/openimagerynetwork/oin-metadata-spec/issues/15. It was agreed that OIN should stay a single license and not open up to multiple licenses. We did discuss that if OAM opens up to other licenses but follows the core imagery metadata spec and standards, then this is good for the ecosystem. 

#### What does this mean for OAM? 

This essentially means if we want to enable multiple license options, we can move forward and work on some ideas for OAM. OAM will still have an OIN bucket that users can upload imagery into for free and it it placed into the commons with an open license. This also means that OAM can look index other sources of imagery that may not have the specific OIN license but want to make their imagery available. 

To work out: 

  * Exposing license information within the UI
  * Do we want to offer users the ability to select a license? If so, OIN imagery will need to be placed into an OIN bucket, other licensed imagery will need to be placed into a separate bucket. 
  * Integrating/indexing other non-OIN sources of imagery, clarifying types of licenses that are compatible with OSM tracing
  * Clarifying language on the frontend UI around use of the non-OIN imagery

Other items to discuss?

**Comment by tombh** [comment]
By the sounds of it, the tech we have in the OIN repos is still setting the precedent for an standardised Imagery Network. So it feels like the OIN might be better named (or moved to a newly named) as the Core Imagery Network (as was suggested by @cholmes?). OIN then just becomes exactly the same as CIN, but with a single license?
