### ISSUE TITLE
Create OAM Logo and Graphics

### ISSUE THREAD

**Issue by cgiovando** [hotosm/OpenAerialMap#7]
Mark Cupitt and I have discussed creating an OAM logo and branding material.

**Comment by cgiovando** [comment]
Here is some imagery from some of my recent aerial surveys that can be used freely for design if needed:

https://drive.google.com/folderview?id=0B1Cz1MHmZTGbcnoyRDY5YWpqOVk&usp=sharing

**Comment by wonderchook** [comment]
Might be useful to also post to the HOT list, there are a few designers there that might not be hanging out on github.

**Comment by ricardomestre** [comment]
I've been taking some initial thoughts on it and already sketched a few logo ideas.

In the meantime, I'm starting the landing page for openaerialmap.org (https://github.com/hotosm/openaerialmap.org) so we can communicate what OAM is.

**Comment by ricardomestre** [comment]
After some initial ideas on paper, here is the work done on the logo.

![oam-logo-versions-1a](https://cloud.githubusercontent.com/assets/1016701/7483984/d6036d60-f351-11e4-8a50-30ff033aab64.png)

With an emphasis on flat design, I aimed for a clean and elegant logo that responds well on multiple sizes and formats.

For the symbol, I tried to capture the idea of a map shaped like a paper plane, for its relation to Aerial Imagery (specially captured by UAVs), Cartography and Openness. The way the paper folds hints a compass needle.

The font in use is Open Sans (Bold weight), a versatile sans-serif typeface designed by Steve Matteson, released under an open license. Available on Google Fonts.

![oam-logo-colors-1a](https://cloud.githubusercontent.com/assets/1016701/7483992/e93cc82c-f351-11e4-8a82-5b811c18d29a.png)

## Process

![oam-logo-construction-grid-1a](https://cloud.githubusercontent.com/assets/1016701/7483995/ed6a87cc-f351-11e4-837c-83a52d26fc42.png)
*Construction grid*

![sketch-01a](https://cloud.githubusercontent.com/assets/1016701/7484006/1bf833be-f352-11e4-93f0-f1caf2d732b2.jpg)
*Sketch*

******

My next step is to work on the UI Toolkit #13 . This logo will inform the colors, fonts and overall aesthetic.

**Comment by smit1678** [comment]
Awesome stuff @ricardomestre. Really like the feel of it.

**Comment by lossyrob** [comment]
I really like the logo. One piece of feedback is, would it be useful to have the logo communicate that this project is about imagery? The OSM-style vector map that is on the paper plane logo makes me thing of OSM and vector data, which might be a slight confusion point vs an intuitive explanation to people trying to grok what the project is really quickly.

**Comment by okiave** [comment]
@ricardomestre thats a clean design for branding/logo. I just discovered this project yesterday and had no problems understanding what it was. In fact the vector design of logo and font made me think it had a touch of Mapbox illustration branding.

On the website there is a visual opportunity to integrate a touch of aerial imagery w/o cluttering up the clean read of the vector logo. Currently the background element for the banner has a zoom out behavior applied with the same vector pattern of the OAM logo. Why not use a clean piece of aerial imagery like the infrared ortho of the colorado river by @cgiovando ? 

You can even add a color overlay that would sample well with the logo colors and would read more like a graphic a because the limited color spectrum from infrared.  

https://drive.google.com/file/d/0B1Cz1MHmZTGbZWprVXEyODlaYzA/view

**Comment by cgiovando** [comment]
I like the idea @okiave - maybe this could be tested as part of the new landing page redesign?

See this thread https://github.com/hotosm/oam-browser/issues/154
