### ISSUE TITLE
Publish OAM Catalog Tech Challenge

### ISSUE THREAD

**Issue by cgiovando** [hotosm/OpenAerialMap#8]
With this tech challenge the Humanitarian OpenStreetMap Team (HOT) is seeking an experienced developer to lead the design and implementation of the OAM imagery catalog. In addition to develop and test the code, the selected winner will also participate in integrating the catalog with other OAM project components.

The draft of the tech challenge call is available >> **[here](https://docs.google.com/document/d/1LvWGDdWJ2RM8iqDVX8nxmZY7IG7SF5B9EeITtjR1JFo/edit?usp=sharing)** << for everyone to contribute and comment.

We would like to publish the tech challenge on **Monday February 16th, 2015**. Please provide your feedback here as comments or in the Google Doc directly.

**Comment by MarkCupitt** [comment]
Ideas proposed by Mark C (Added to the Document)

Don’t suggest Python as a requirement of preferred. Lots of other options. I suspect that it will end up as a Python Rail/Django style implementation, because of the Open Source Nature, but let developers see what they can offer in other languages/frameworks, in fact I would suggest encouraging that to see if anything interesting pops up

I also think you may want to consider requiring that the whole thing be driven by an Api and split out the front end development from the back end as two separate projects. Developers who are good at Back End stuff, are generally not great at user interfaces and vice-versa. The first part of the project should be designing and publishing the API, what it does, then fit the Back End to that and develop the Front End in Parallel to the Back End.

**Comment by dodobas** [comment]
@MarkCupitt you DO want to suggest technology stack that has a big enough developer pool. you DO NOT want to choose something interesting that no one in the HOT community understands/use, because once the developer contract ends HOT community should be able continue supporting and developing the project

also, you want to use technologies that are relatively simple to learn and extend so junior developers and interns can contribute

**Comment by wonderchook** [comment]
Agreed with @dodobas for HOT to continue to support projects we need to standardize on language/framework. We shouldn't be adding new ones, for existing projects obviously they are written in whatever they are written in.

**Comment by MarkCupitt** [comment]
@dodobas @wonderchook I am in 100% agreement. I am not aware if there is any standard for HOT yet. I thought that this OAM project would be an ideal opportunity to see what was out there and broaden the options somewhat. 

I would expect that whatever decision is made about the technology stack for OAM, will indeed, and hopefully, become the standard. There are a lot of great options out there we should look at as many as we can.

If a Technology Stack is chosen that is very good but only a few people can use it, it could be counter productive and limit community input if everyone has to learn it from scratch. People do have time limitations ..

I do not contribute to TM2, I would love to, but I just do not have the time to learn Pyramid. I am sure there are a lot of developers out there who are the same.

My suggestion was along the lines to not write off more mainstream options as they may offer more opportunities to get community development involvement in HOT projects (eg: NodeJS, PHP, Postgres/PostGis, etc)

Whatever the decision is, and if the technology stack is published as official and to be used in the future for all HOT Projects, I would be more than happy to invest time and effort learning it so I could contribute .. 

Obviously, there will never be a perfect solution, simply does not exist ..

**Comment by wildintellect** [comment]
It's tricky picking one and only one option may prove to be difficult to shoe-horn everything. In this case the discussion is really around web frameworks. Any well supported open source framework should work, but obviously there might be some bias within the potential community. Work with the candidates to narrow the choices, and then solicit feedback from the potential contributors. Database really shouldn't play in, if it's really a good framework it's realatively db agnostic. Obviously some framework have more direct support for geospatial components.

In terms of potential contributors, they will all have their preferences/experience. However jumping between well designed frameworks should not be a stopper. The really good programmers have done something in almost all of them, and can get up to speed quickly. The question is the more casual contributors. I suspect if the products are modular enough that getting help on various parts would not be hard, e.g: db tasks for db people, js/html/css tasks for frontend people, etc..

It seems reasonable to me to include suggested acceptable languages under which the work should be done.

**Comment by cgiovando** [comment]
Call was published and Development Seed was selected.
