### ISSUE TITLE
Consolidating docs

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenAerialMap#86]
Problem: we have documentation spread around quite a bit. Some API documentation in apidocjs format and some documentation in markdown on https://github.com/hotosm/oam-docs. In addition, our current documentation site is geared around the components of OAM and not fully about onboarding users. 

Along with our repo consolidation, it would be good to revisit how we're managing our documentation. 

Proposing to consolidate into three sections: 

### 1. API documentation all together

Do we want to continue to use the APIDOCs format and style: http://hotosm.github.io/oam-catalog/? Or switch to managing the documentation differently like through Gitbooks ([example](https://developer.gitbook.com/))? This could be done within the same repo, just through a `/docs` folder. 

### 2. User Guides 

In additional to some written user guides, we plan to do some videos explaining functionalities, how to upload, and other ways to use features. 

### 3. New addition - FAQs

I think it might be interesting to add an FAQs section. Could be able to drop in a lot of various questions to be able to serve as a knowledge base for new users. Example FAQ gitbook: https://smit1678.gitbooks.io/my-faqs/content/. 

Other suggestions @cgiovando @mojodna @tombh @sharkinsspatial @brendangatens?

**Comment by tombh** [comment]
Yes, very supportive of this. I love the simple layout of Gitbooks and the accessibility of markdown.

But I'd definitely like to see a move to [Swagger](https://github.com/glennjones/hapi-swagger) from the current `apidoc` stuff we have. Swagger actually builds the docs from the _code_, not from the comments in the code - so the docs are guaranteed to be accurate and up to date. A quick google shows that there is a [Swagger to Gitbooks converter](https://github.com/gnomeontherun/gitbook-plugin-swagger), so that could be an option to keep everything under one roof.

I would also like to see the docs repo moved to the frontend repo. It will reduce the fragmentation of OAM ecosystem, but also be more likely to encourage the update of docs when the corresponding code changes at the point of commit.

**Comment by smit1678** [comment]
> But I'd definitely like to see a move to Swagger from the current apidoc stuff we have.

👍 cool, I think that's a good idea too. I think that would put this in line with https://github.com/radiantearth/catalog-api-spec/tree/dev/implementations

**Comment by smit1678** [comment]
@tombh Coming back to your comment about Swagger. Did you move the new `oauth-login` branch to Swagger? If not, can you open a ticket about outlining what needs to be done there?

**Comment by tombh** [comment]
Done. See  hotosm/oam-catalog#111
